# Generated by Django 6.0.3 on 2026-03-27 13:07

from django.db import migrations, models


def backfill_article_status(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    Article.objects.filter(approved=True).update(status='published')
    Article.objects.filter(approved=False).update(status='pending_review')


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_story_image_article_weather_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='editor_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.tag'),
        ),
        migrations.RunPython(backfill_article_status, migrations.RunPython.noop),
    ]
